version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: seafile_db_root_password
      MYSQL_DATABASE: seafile_db
      MYSQL_USER: seafile_user
      MYSQL_PASSWORD: seafile_password
    volumes:
      - ./db_data:/var/lib/mysql

  seafile:
    image: seafileltd/seafile:latest
    environment:
      SEAFILE_ADMIN_PASSWORD: your_admin_password
      SEAFILE_DB_HOST: db
      SEAFILE_DB_ROOT_PASS: seafile_db_root_password
      SEAFILE_DB_NAME: seafile_db
      SEAFILE_DB_USER: seafile_user
    ports:
      - "8055:80"
    volumes:
      - ./seafile_data:/opt/seafile
    depends_on:
      - db

volumes:
  db_data:
  seafile_data:
