version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8799:80"  # 将容器的 80 端口映射到主机的 8080 端口
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_PASSWORD: examplepassword  # 数据库密码
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_HOST: db
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword  # MariaDB root 密码
      MYSQL_PASSWORD: examplepassword      # Nextcloud 数据库密码
      MYSQL_DATABASE: nextcloud            # Nextcloud 使用的数据库名
      MYSQL_USER: nextclouduser            # Nextcloud 数据库用户名
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  nextcloud_data:
  db_data:
