version: '3'
services:
  mysql8_demo:
    image: mysql:8.0
    container_name: mysql8_demo_cn
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_DATABASE=blog
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    networks:
      - mysql8_demo_net
  mysql8_demo_admin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql8_demo_admin_cn
    ports:
      - "3308:80"
    environment:
      - PMA_ARBITRARY=0
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql8_demo_cn
    depends_on:
      - mysql8_demo
    networks:
      - mysql8_demo_net

networks:
  mysql8_demo_net:
    driver: bridge

