version: '3'

services:
  filerun:
    image: filerun/filerun:8.1
    ports:
      - "8050:80"
    volumes:
      - /filerun/html=/var/www/html
      - /filerun/user-files=/user-files
    environment:
      - FR_DB_HOST=db
      - FR_DB_PORT=3306
      - MYSQL_PASSWORD=filerun
      - MYSQL_DATABASE=filerun
      - MYSQL_USER=filerun
      - MYSQL_ROOT_PASSWORD=root
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_USER_ID=33
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    links:
      - db:db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=filerun
      - MYSQL_USER=filerun
      - MYSQL_PASSWORD=filerun
    volumes:
      - ./db-data:/var/lib/mysql
